import HomeButton from "./components/HomeButton";
import "./globals.css";
import { useRouter } from "next/navigation";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-cyan-50">
        <div className="w-[100vw] h-[100vh] grid grid-rows-[auto_1fr_auto]">
          <div className="h-[40px] p-2 grid grid-cols-[1fr_auto] justify-between items-center">
            <div>Welcome to the Demo App</div>
            <div className="px-2.5">
              <HomeButton />
            </div>
          </div>
          <div className="p-2">{children}</div>
          <div className="p-2">Footer</div>
        </div>
      </body>
    </html>
  );
}
